### ISSUE TITLE
项目下载下来后，运行不起来。

### ISSUE THREAD

**Issue by wty302857194** [Littleor/iWidget#1]
feedkit找不到

**Comment by Littleor** [comment]
> feedkit找不到

使用Swift Packages下载就可以了
<img width="1042" alt="Screen Shot 2020-07-13 at 11 04 35" src="https://user-images.githubusercontent.com/51821219/87266783-a658ea80-c4f8-11ea-8547-7023931fe606.png">

**Comment by wty302857194** [comment]
怎么下载呢？

我看swift packages下面是有的呀

**Comment by Littleor** [comment]
> 怎么下载呢？
> 
> 我看swift packages下面是有的呀

报错具体内容是?

**Comment by wty302857194** [comment]
Resolve Package Graph
: An unknown error occurred
Fetching https://github.com/nmdias/FeedKit/


/Users/circlecan/Downloads/iWidget-main/iWidget.xcodeproj Missing package product 'FeedKit'

**Comment by Littleor** [comment]
> Resolve Package Graph
> : An unknown error occurred
> Fetching https://github.com/nmdias/FeedKit/
> 
> /Users/circlecan/Downloads/iWidget-main/iWidget.xcodeproj Missing package product 'FeedKit'

解决方案见:

https://stackoverflow.com/questions/60952549/xcode-11-4-compile-error-missing-package-product-package-name

> 直接File > Swift Packages > Reset Package Caches或 File > Swift Packages > Update to Latest Package Versions即可
