### ISSUE TITLE
很赞的项目，提个建议

### ISSUE THREAD

**Issue by sunjianan9900** [Littleor/iWidget#10]
如果能有和项目数据交互的小组件demo就好了
比如点击编辑选择显示数据，数据来自于app内用户自编辑的内容
例如便签、绘制的图等

**Comment by Littleor** [comment]
最近在忙比赛，很抱歉现在才回复。
首先你指的是能和APP内的数据交互吧，就如你所说能在APP内设置便签、绘图、选择图片然后展示到部件。
这是可以通过APP和Widget数据共享做到的，同时这个建议已经在做了，具体例子请等待 [Widget Center](https://apps.apple.com/cn/app/id1522986813) 更新APP内背景和内容配置后再迁移到iWidget并可能会在博客出一期分享。
