### ISSUE TITLE
关于刷新的问题

### ISSUE THREAD

**Issue by 2697a** [Littleor/iWidget#11]
你好，如果想实现时钟效果，一秒刷新一次要怎么实现呢？

**Comment by Littleor** [comment]
> 你好，如果想实现时钟效果，一秒刷新一次要怎么实现呢？

这个应该直接改timeline的时间就可以实现把？
具体我没有实践过，请自行测试是否可行。

**Comment by Unchanged-Is-Changed** [comment]
> > 你好，如果想实现时钟效果，一秒刷新一次要怎么实现呢？
> 
> 这个应该直接改timeline的时间就可以实现把？
> 具体我没有实践过，请自行测试是否可行。

每秒钟刷新 审核会被拒绝吗
