### ISSUE TITLE
数据获取

### ISSUE THREAD

**Issue by doudouBigData** [Littleor/iWidget#12]
你好！我最近在开发小组件，数据是app中的一个列表页的数据，我的问题是我怎么请求这个接口给小组件用？我也想过很多方案但是都打败了，我想听听你的建议：

1、我想把app（oc）中的网络库和小组件公用，但是编译不成功。
2、我想通过app groups 共享数据，但是app没有启动或者长时间不更新数据，小组件的数据没有很好的及时性。

**Comment by Littleor** [comment]
你好我想问下这个App列表的数据是来自后端API的数据吗，如果是的话在oc无法和小组件共享库的情况下建议使用Swift来请求一下API来获取数据再展示（这也是我个人觉得更好的方式，具体的可以参考下iWidget的一言部件，写的很简单很容易上手）

如果该数据是需要App一系列操作的数据，还是建议使用App Group共享吧，不过这样的话就会导致你说的更新不及时的问题，暂时想到的解决方案如下：
1.App操作后，通过WidgetKit的API通知小部件更新（这个适用于你的数据是要App操作后才更新）
2.通过App Group来完成数据共享，App操作后更新Group内的数据然后等待部件更新。（这个是目前iWidget负一屏部件用的方式）

> 主要是不大了解你的具体情况故可能无法给出满意的答案，上述仅供参考。
