### ISSUE TITLE
为啥不更新了呀

### ISSUE THREAD

**Issue by AlanDinkle** [Littleor/iWidget#14]
简约实用美观

**Comment by Littleor** [comment]
感谢认可，没有更新的主要原因在于近期生活上的事情较为繁杂，没有过多精力去继续维护，目前设计上难以达到预期，所以近期暂停了该项目的推进，后续有机会的话会继续带来一些优雅的小部件。

如果你喜欢这个项目的话也可以继续发挥创造力，欢迎提PR~
