### ISSUE TITLE
关于加载网络图片的问题

### ISSUE THREAD

**Issue by fakeros** [Littleor/iWidget#2]
hi，我在你的demo的基础上，尝试去加载网络图，发现图片下载完成之后并不能生效，但是同样的代码在主工程是可以生效的，请问widget中如何去加载网络图？

<img width="713" alt="截屏2020-07-13 下午4 29 29" src="https://user-images.githubusercontent.com/7323942/87281695-10d44f80-c526-11ea-890f-b2fc0780ad6b.png">

**Comment by Littleor** [comment]
> hi，我在你的demo的基础上，尝试去加载网络图，发现图片下载完成之后并不能生效，但是同样的代码在主工程是可以生效的，请问widget中如何去加载网络图？
> 
> <img alt="截屏2020-07-13 下午4 29 29" width="713" src="https://user-images.githubusercontent.com/7323942/87281695-10d44f80-c526-11ea-890f-b2fc0780ad6b.png">

如果我没理解错的话，你是在onAppear的时候调用了下载图片的函数来加载图片,而这个时候View已经显示了哦,我之前好像是发现在Widget里面将不会刷新View当你在View里面改变的时候.

> 所以我建议你把加载图片的过程放在Timeline中刷新View前执行(如该项目中的一言小部件一样)，这个时候应该就不会有这个问题了。

**Comment by fakeros** [comment]
谢谢，按照你的建议，确实可以。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Littleor/iWidget"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月13日(星期一) 下午4:46
收件人:&nbsp;"Littleor/iWidget"<iWidget@noreply.github.com&gt;;
抄送:&nbsp;"小狼"<809146485@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Littleor/iWidget] 关于加载网络图片的问题 (#2)





  
hi，我在你的demo的基础上，尝试去加载网络图，发现图片下载完成之后并不能生效，但是同样的代码在主工程是可以生效的，请问widget中如何去加载网络图？
   
如果我没理解错的话，你是在onAppear的时候调用了下载图片的函数来加载图片,而这个时候View已经显示了哦,我之前好像是发现在Widget里面将不会刷新View当你在View里面改变的时候.
  
所以我建议你把加载图片的过程放在Timeline中刷新View前执行(如该项目中的一言小部件一样)，这个时候应该就不会有这个问题了。
