### ISSUE TITLE
xcode12 beta3 真机不显示widget

### ISSUE THREAD

**Issue by fakeros** [Littleor/iWidget#3]
下载xcode12 beta3，真机启动会崩溃，模拟器正常

<img width="702" alt="截屏2020-07-29 下午8 46 58" src="https://user-images.githubusercontent.com/7323942/88802221-58710180-d1dd-11ea-9d68-47fd4c248dcb.png">

**Comment by Littleor** [comment]
> 下载xcode12 beta3，真机启动会崩溃，模拟器正常
> 
> <img alt="截屏2020-07-29 下午8 46 58" width="702" src="https://user-images.githubusercontent.com/7323942/88802221-58710180-d1dd-11ea-9d68-47fd4c248dcb.png">

真机的版本号能提供下吗

**Comment by fakeros** [comment]
iOS14.0 beta版

**Comment by Littleor** [comment]
> iOS14.0 beta版

beta3吗？

**Comment by fakeros** [comment]
我用的第iOS14第一个beta1版本，发现在xcode12 beta3上会有问题，把iOS14升级到beta3版本，就正常了

**Comment by Littleor** [comment]
> 我用的第iOS14第一个beta1版本，发现在xcode12 beta3上会有问题，把iOS14升级到beta3版本，就正常了
> 
> 

beta3更新的时候估计更新了widgetkit

**Comment by taroYxx** [comment]
在iOS4的widget中添加OC的文件报错  有人知道怎么解决吗？

**Comment by josercc** [comment]
我的运行到真机不显示 模拟器可以正常

**Comment by Littleor** [comment]
> 我的运行到真机不显示 模拟器可以正常

系统版本号多少？

**Comment by 425589643** [comment]
我最新系统，真机不显示，模拟器显示，又遇到么
