### ISSUE TITLE
在iOS4的widget中添加OC的文件报错你是怎么处理的？

### ISSUE THREAD

**Issue by OnlyJeremy** [Littleor/iWidget#4]
在iOS4的widget中添加OC的文件报错，然后做了桥接还是解决不了问题，求解

**Comment by taroYxx** [comment]
我也是  在iOS4的widget中添加OC的文件报错 这个好坑啊

**Comment by Littleor** [comment]
你们有添加**classfix**吗？
可能是这个的锅

**Comment by OnlyJeremy** [comment]
> 你们有添加**classfix**吗？
> 可能是这个的锅

我试了把classfix去除了也不行啊。

**Comment by OnlyJeremy** [comment]
> 我也是 在iOS4的widget中添加OC的文件报错 这个好坑啊

你现在找到原因了吗？加我qq：737632008沟通下啊

**Comment by josercc** [comment]
不是只SwiftUI吗 添加OC是什么操作？

**Comment by Littleor** [comment]
> 不是只SwiftUI吗 添加OC是什么操作？

Widgetkit只支持SwiftUI，这就导致原有的一些OC项目是无法使用的。
所以就用老办法在OC和Swift之间搭桥来首实现
