### ISSUE TITLE
onBackgroundURLSessionEvents 这个提供的api是啥意思 咋没用呢 我看你项目中也没用

### ISSUE THREAD

**Issue by sunforcode** [Littleor/iWidget#5]

**Comment by Littleor** [comment]
首先我们参考下[官方文档](https://developer.apple.com/documentation/widgetkit/intentconfiguration/onbackgroundurlsessionevents(matching:_:)-78bry)
其中有这样一句话：
> When a widget initiates a background network request, the system delivers events related to the request directly to the widget extension instead of the containing app.

在官方文档中，指出了该方法可用来给Widget处理需要下载文件时候，通过这个方法让Widget Extension去执行后台下载，当Widget Extension执行完成后调用urlSessionDidFinishEvents方法来让widget继续执行下载后的代码。
个人的理解是相当于Widget可以通过这个方法委托Widget Extension完成网络请求，避免Widget长时间的网络请求，当Widget Extension完成委托任务后调用方法通知委托人(Widget)完成Widget的刷新。
> 该API并没有用于iWidget，因为iWidget并没有太多网络开销，所以采用了直接请求完成后再调用时间线刷新的方法。

**Comment by sunforcode** [comment]
我测试只有一次能够成功的得到后台给的响应,不知道这个后台任务如果定义,只能下载任务嘛 datatask貌似不在这个范围内.找了全网没有好的答案

**Comment by Littleor** [comment]
> 我测试只有一次能够成功的得到后台给的响应,不知道这个后台任务如果定义,只能下载任务嘛 datatask貌似不在这个范围内.找了全网没有好的答案

你好 首先很抱歉过了这么多天才回复，最近有点忙这两天才开始研究如何在WidgetKit上使用图片，然后就开始了解onBackgroundURLSessionEvents这个API，这个API是用来后台下载的，如[这篇文章](https://developer.apple.com/documentation/foundation/url_loading_system/downloading_files_in_the_background#overview)所说的一样，而且这个API并非iOS14新API。
所以我很疑惑，为什么你会在这个项目里提出这个API的疑惑，该API位于*Foundation*下，具体可以参考官方文档
