### ISSUE TITLE
关于添加组件选择尺寸的页面，模拟器显示黑色的问题。

### ISSUE THREAD

**Issue by pcccccc** [Littleor/iWidget#6]
首先十分感谢您，在您的项目中学习到了Widget的使用。

目前我暂时没有iOS14的真机可以使用，所以想请问一下您，下图这种情况在真机是否存在。

![QQ20200907-175130](https://user-images.githubusercontent.com/13974510/92374906-fb992d00-f132-11ea-9525-5b1e93908206.png)

如果已存在，如何避免这种黑屏问题，目前是否有解决方案。

非常感谢。

**Comment by Littleor** [comment]
你好 首先感谢你的测试
然后真机第一次使用部件的时候也会出现该种情况，目前暂时认为是iOS14beta的偶发性bug
之后使用就会显示正常了
因为iOS14调整过Placeholder的API，iWidget已经适配了新的API所以暂时没有发现解决方法，得等待iOS发布新beta

**Comment by pcccccc** [comment]
> 你好 首先感谢你的测试
> 然后真机第一次使用部件的时候也会出现该种情况，目前暂时认为是iOS14beta的偶发性bug
> 之后使用就会显示正常了
> 因为iOS14调整过Placeholder的API，iWidget已经适配了新的API所以暂时没有发现解决方法，得等待iOS发布新beta

十分感谢您的解答，我也会继续学习您的项目。

**Comment by pcccccc** [comment]
您好，我今天更新了GM版本，发现了解决方案。
或许您可以尝试一下在func getSnapshot中设置一个请求去刷新页面。就可以解决这个问题。

**Comment by Littleor** [comment]
> 您好，我今天更新了GM版本，发现了解决方案。
> 或许您可以尝试一下在func getSnapshot中设置一个请求去刷新页面。就可以解决这个问题。

很遗憾，这个问题并没有被解决，目前我在 《部件中心》中尝试了该方法，但是依旧第一次开始加载的时候还是黑色，后面就不会了

**Comment by pcccccc** [comment]
> > 您好，我今天更新了GM版本，发现了解决方案。
> > 或许您可以尝试一下在func getSnapshot中设置一个请求去刷新页面。就可以解决这个问题。
> 
> 很遗憾，这个问题并没有被解决，目前我在 《部件中心》中尝试了该方法，但是依旧第一次开始加载的时候还是黑色，后面就不会了

目前根据我已有的经验，黑屏可能是因为您的组件中某个设置项或从网络请求的数据以及默认数据可能为空，会导致黑屏。我已经将此错误修复，您可以尝试一下。
