### ISSUE TITLE
真机不显示，模拟器显示  又遇到的吗

### ISSUE THREAD

**Issue by 425589643** [Littleor/iWidget#7]
真机不显示，模拟器显示  又遇到的吗

**Comment by Littleor** [comment]
你好请具体给出Xcode和真机的版本号
然后Widget的话需要运行一遍APP才会显示

**Comment by MxlZlh** [comment]
我也是真机不显示，模拟器显示。请问怎么解决？
真机：iPhone7Plus 14.1
Xcode: 12.1

**Comment by MxlZlh** [comment]
真机上，APP运行之后Widget依然不显示
