### ISSUE TITLE
你好，我在使用NavigationView 时无法跳转,控制台报错，可是在你的项目中就没有这个问题，请问啥原因

### ISSUE THREAD

**Issue by Xiaxiangjing** [Littleor/iWidget#8]
var body: some View {
    
        NavigationView{
            
            Text("Hello, world!")
            
        }.onOpenURL { (url) in
            
            UIApplication.shared.open(url)   
        }
    }

报错如下：
 Cannot use Scene methods for URL, NSUserActivity, and other External Events without using SwiftUI Lifecycle. Without SwiftUI Lifecycle, advertising and handling External Events wastes resources, and will have unpredictable results.

**Comment by Littleor** [comment]
你好我目前暂时从未遇到该问题，请问你的Xcode版本和构建版本是多少呢？
我查找过一些资料发现很多人在最新的Xcode12 beta上会遇到该问题，暂时认为是Xcode的bug，详见:
[SwiftUI External Events without SwiftUI Lifecycle](https://developer.apple.com/forums/thread/658501)
[Cannot use Scene methods for URL, NSUserActivity, and other External Events without using SwiftUI Lifecycle
](https://stackoverflow.com/questions/63599959/cannot-use-scene-methods-for-url-nsuseractivity-and-other-external-events-with)
