### ISSUE TITLE
这个是什么错误？

### ISSUE THREAD

**Issue by isgbuddy** [Littleor/iWidget#9]
<img width="1278" alt="截屏2020-10-08 下午5 24 19" src="https://user-images.githubusercontent.com/13424995/95440483-9469d500-098b-11eb-98d1-9dc8a73e0f80.png">

**Comment by Littleor** [comment]
Result是Swift自带的class啊，盲猜Xcode的bug，建议Clean下Build Folder然后重启下Xcode吧。

**Comment by isgbuddy** [comment]
嗯，重新 build 一下好了，谢谢了
